src/main/java/pl/edu/pwr/student200275/ejb/EnterpriseCustomersBean.java
package pl.edu.pwr.student200275.ejb;

import java.util.Date;
import java.util.List;

import javax.ejb.EJB;
import javax.ejb.Singleton;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import pl.edu.pwr.student200275.jpa.Customer;
import pl.edu.pwr.student200275.jpa.Equipment;
import pl.edu.pwr.student200275.jpa.Order;

@Singleton
public class EnterpriseCustomersBean {

	@PersistenceContext
	private EntityManager em;

	@EJB
	private EnterpriseEquipmentBean eqEjb;

	public List<Customer> getList() {
		Logger.log("EnterpriseCustomersBean.getList()." + System.nanoTime());
		return em.createQuery("from Customer c left join fetch c.orders o order by c.id asc", Customer.class).getResultList();
	}

	public Customer get(Long id) {
		Logger.log("EnterpriseCustomersBean.get(" + id + ")." + System.nanoTime());
		Customer cust = em.find(Customer.class, id);
		cust.getOrders().size();
		return cust;
	}

	public Customer add(Customer customer) {
		Logger.log("EnterpriseCustomersBean.add(...)." + System.nanoTime());
		em.persist(customer);
		return customer;
	}

	public void update(Customer customer) {
		Logger.log("EnterpriseCustomersBean.update(...)." + System.nanoTime());
		Customer cust = em.find(Customer.class, customer.getId());
		cust.setCity(customer.getCity());
		cust.setName(customer.getName());
		cust.setPhone(customer.getPhone());
		cust.setStreet(customer.getStreet());
		cust.setZipCode(customer.getZipCode());
	}

	public void createOrder(Long customerId, Long equipmentId) {
		Logger.log("EnterpriseCustomersBean.createOrder(" + customerId + "," + equipmentId + ")." + System.nanoTime());
		Customer customer = get(customerId);
		Equipment equipment = eqEjb.get(equipmentId);
		Order order = new Order();
		order.setCustomer(customer);
		order.setEquipment(equipment);
		order.setStartDate(new Date());
		em.persist(order);
		equipment.setAvailable(false);
	}

	public void finishOrder(Long orderId) {
		Logger.log("EnterpriseCustomersBean.finishOrder(" + orderId + ")." + System.nanoTime());
		Order order = em.find(Order.class, orderId);
		order.setEndDate(new Date());
		order.getEquipment().setAvailable(true);
	}

	public List<Order> getUnfinishedOrders(Long id) {
		Logger.log("EnterpriseCustomersBean.getUnfinishedOrders(" + id + ")." + System.nanoTime());
		return em.createQuery(
				"from Order o join fetch o.customer c where o.endDate = null and c.id=:custId order by o.id asc",
				Order.class).setParameter("custId", id).getResultList();
	}

	public List<Order> getOrders(Long custId) {
		Logger.log("EnterpriseCustomersBean.getOrders(" + custId + ")." + System.nanoTime());
		if (custId == null) {
			return em.createQuery("from Order o join fetch o.customer c order by o.id desc", Order.class)
					.getResultList();
		} else {
			return em.createQuery("from Order o join fetch o.customer c where c.id = :custId order by o.id desc",
					Order.class).setParameter("custId", custId).getResultList();
		}
	}

	public Order getOrder(Long id) {
		Logger.log("EnterpriseCustomersBean.getOrder(" + id + ")." + System.nanoTime());
		return em.find(Order.class, id);
	}

	public void updateOrder(Long id, Long customerId, Long equipmentId) {
		Logger.log("EnterpriseCustomersBean.updateOrder(" + id + "," + customerId + "," + equipmentId + ")."
				+ System.nanoTime());
		Order order = getOrder(id);
		if (!order.getEquipment().getId().equals(equipmentId)) {
			order.getEquipment().setAvailable(true);
			Equipment equipment = eqEjb.get(equipmentId);
			order.setEquipment(equipment);
			equipment.setAvailable(false);
		}
		Customer customer = get(customerId);
		order.setCustomer(customer);
		em.persist(order);
	}
}

src/main/java/pl/edu/pwr/student200275/ejb/EnterpriseEquipmentBean.java
package pl.edu.pwr.student200275.ejb;

import java.util.List;

import javax.ejb.Singleton;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import pl.edu.pwr.student200275.jpa.Equipment;

@Singleton
public class EnterpriseEquipmentBean {

	@PersistenceContext
	private EntityManager em;

	public List<Equipment> getList() {
		return em.createQuery("from Equipment e order by e.id asc", Equipment.class).getResultList();
	}

	public Equipment get(Long id) {
		return em.find(Equipment.class, id);
	}

	public Equipment add(Equipment equipment) {
		em.persist(equipment);
		return equipment;
	}

	public void update(Equipment equipment) {
		Equipment eq = em.find(Equipment.class, equipment.getId());
		eq.setName(equipment.getName());
	}

	public List<Equipment> getAvailable() {
		return em.createQuery("from Equipment e where e.available=true order by e.id asc", Equipment.class)
				.getResultList();
	}
}

src/main/java/pl/edu/pwr/student200275/jsf/FacesCustomerBean.java
package pl.edu.pwr.student200275.jsf;

import java.io.Serializable;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.inject.Inject;

import pl.edu.pwr.student200275.ejb.EnterpriseCustomersBean;
import pl.edu.pwr.student200275.ejb.Logger;
import pl.edu.pwr.student200275.jpa.Customer;

@ManagedBean
@RequestScoped
public class FacesCustomerBean implements Serializable{
	private static final long serialVersionUID = 7803202834533286888L;

	@Inject
	private EnterpriseCustomersBean ejb;

	private Long id;
	private String customerName;
	private String customerStreet;
	private String customerCity;
	private String customerPhone;
	private String customerZipCode;

	private void loadCustomer() {
		if (customerName == null && id != null) {
			Logger.log("FacesCustomerBean.getCustomer()." + System.nanoTime());
			Customer customer = ejb.get(id);
			customerName = customer.getName();
			customerCity = customer.getCity();
			customerPhone = customer.getPhone();
			customerStreet = customer.getStreet();
			customerZipCode = customer.getZipCode();
			Logger.log("FacesCustomerBean.getCustomer()." + System.nanoTime());
		}
	}

	public String save() {
		if (id != null) {
			Logger.log("FacesCustomerBean.save()." + System.nanoTime());
			Customer cust = new Customer();
			cust.setId(id);
			cust.setName(customerName);
			cust.setCity(customerCity);
			cust.setPhone(customerPhone);
			cust.setZipCode(customerZipCode);
			cust.setStreet(customerStreet);
			ejb.update(cust);
			return "customer.xhtml?faces-redirect=true&id=" + id;
		}
		return null;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getCustomerName() {
		loadCustomer();
		return customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public String getCustomerStreet() {
		loadCustomer();
		return customerStreet;
	}

	public void setCustomerStreet(String customerStreet) {
		this.customerStreet = customerStreet;
	}

	public String getCustomerCity() {
		loadCustomer();
		return customerCity;
	}

	public void setCustomerCity(String customerCity) {
		this.customerCity = customerCity;
	}

	public String getCustomerPhone() {
		loadCustomer();
		return customerPhone;
	}

	public void setCustomerPhone(String customerPhone) {
		this.customerPhone = customerPhone;
	}

	public String getCustomerZipCode() {
		loadCustomer();
		return customerZipCode;
	}

	public void setCustomerZipCode(String customerZipCode) {
		this.customerZipCode = customerZipCode;
	}

}

src/main/java/pl/edu/pwr/student200275/jsf/FacesCustomersBean.java
package pl.edu.pwr.student200275.jsf;

import java.io.Serializable;
import java.util.Collection;
import java.util.List;
import java.util.stream.Collectors;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.model.SelectItem;
import javax.inject.Inject;

import pl.edu.pwr.student200275.ejb.EnterpriseCustomersBean;
import pl.edu.pwr.student200275.ejb.Logger;
import pl.edu.pwr.student200275.jpa.Customer;

@ManagedBean
@RequestScoped
public class FacesCustomersBean implements Serializable {
	private static final long serialVersionUID = 5595881483859585881L;

	@Inject
	private EnterpriseCustomersBean ejb;

	private Long id;
	private Long equipmentId;
	private Long orderId;
	private String action;
	private Customer customer;
	private String customerName;
	private String customerStreet;
	private String customerCity;
	private String customerPhone;
	private String customerZipCode;

	public String save() {
		Logger.log("FacesCustomersBean.save()." + System.nanoTime());
		if (customer.getId() == null) {
			id = ejb.add(customer).getId();
		} else {
			customer.setName(customerName);
			customer.setPhone(customerPhone);
			customer.setCity(customerCity);
			customer.setZipCode(customerZipCode);
			customer.setStreet(customerStreet);
			ejb.update(customer);
		}
		return "customers.xhtml?faces-redirect=true&action=view&id=" + id;
	}

	public String saveOrder() {
		Logger.log("FacesCustomersBean.saveOrder()." + System.nanoTime());
		ejb.createOrder(id, equipmentId);
		return "customers.xhtml?faces-redirect=true&action=view&id=" + id;
	}

	public String finishOrder() {
		Logger.log("FacesCustomersBean.finishOrder()." + System.nanoTime());
		if (orderId != null)
			ejb.finishOrder(orderId);
		return "customers.xhtml?faces-redirect=true&action=view&id=" + id;
	}

	public List<SelectItem> getUnfinishedOrders() {
		Logger.log("FacesCustomersBean.getUnfinishedOrders()." + System.nanoTime());
		return ejb.getUnfinishedOrders(id).stream().map(o -> {
			return new SelectItem(o.getId(), o.getEquipment().getName());
		}).collect(Collectors.toList());
	}

	public boolean isViewAction() {
		return ("newOrder".equals(action) || "finishOrder".equals(action) || "view".equals(action)) && id != null;
	}

	public boolean isDisplayForm() {
		return ("edit".equals(action) && id != null) || "add".equals(action);
	}

	public boolean isDisplayOrderForm() {
		return "newOrder".equals(action);
	}

	public boolean isDisplayDetailsSection() {
		return id != null || "add".equals(action);
	}

	public String getAction() {
		return action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public Collection<Customer> getCustomers() {
		Logger.log("FacesCustomersBean.getCustomers()." + System.nanoTime());
		List<Customer> list = ejb.getList();
		return list;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Customer getCustomer() {
		loadCustomer();
		return customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Long getEquipmentId() {
		return equipmentId;
	}

	public void setEquipmentId(Long equipmentId) {
		this.equipmentId = equipmentId;
	}

	private void loadCustomer() {
		Logger.log("FacesCustomersBean.loadCustomer()." + System.nanoTime());
		customer = ejb.get(id);
		customerName = customer.getName();
		customerCity = customer.getCity();
		customerPhone = customer.getPhone();
		customerStreet = customer.getStreet();
		customerZipCode = customer.getZipCode();
	}

	public Long getOrderId() {
		return orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	public String getCustomerName() {
		return customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public String getCustomerStreet() {
		return customerStreet;
	}

	public void setCustomerStreet(String customerStreet) {
		this.customerStreet = customerStreet;
	}

	public String getCustomerCity() {
		return customerCity;
	}

	public void setCustomerCity(String customerCity) {
		this.customerCity = customerCity;
	}

	public String getCustomerPhone() {
		return customerPhone;
	}

	public void setCustomerPhone(String customerPhone) {
		this.customerPhone = customerPhone;
	}

	public String getCustomerZipCode() {
		return customerZipCode;
	}

	public void setCustomerZipCode(String customerZipCode) {
		this.customerZipCode = customerZipCode;
	}

	public List<SelectItem> getCustomersSelectItemList() {
		Logger.log("FacesCustomersBean.getCustomersSelectItemList()." + System.nanoTime());
		return ejb.getList().stream().map(cust -> {
			return new SelectItem(cust.getId(), cust.getName());
		}).collect(Collectors.toList());
	}
}

src/main/java/pl/edu/pwr/student200275/jsf/FacesEmptyBean.java
package pl.edu.pwr.student200275.jsf;

import java.io.Serializable;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.inject.Inject;

import pl.edu.pwr.student200275.ejb.DbFiller;
import pl.edu.pwr.student200275.ejb.Logger;

@ManagedBean
@SessionScoped
public class FacesEmptyBean implements Serializable {
	private static final long serialVersionUID = -4337412669831457133L;

	@Inject
	DbFiller ejb;
	
	public String getHelloWorld() {
		Logger.log("FacesEmptyBean.helloWorld()." + System.nanoTime());
		return ejb.helloWorld();
	}

}

src/main/java/pl/edu/pwr/student200275/jsf/FacesEquipmentBean.java
package pl.edu.pwr.student200275.jsf;

import java.io.Serializable;
import java.util.Collection;
import java.util.List;
import java.util.stream.Collectors;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.model.SelectItem;
import javax.inject.Inject;

import pl.edu.pwr.student200275.ejb.EnterpriseEquipmentBean;
import pl.edu.pwr.student200275.jpa.Equipment;

@ManagedBean
@RequestScoped
public class FacesEquipmentBean implements Serializable {
	private static final long serialVersionUID = 6485643313093259275L;

	@Inject
	private EnterpriseEquipmentBean ejb;

	private Long id;
	private String action;
	private Equipment equipment;

	public String save() {
		if (equipment.getId() == null) {
			id = ejb.add(equipment).getId();
		} else {
			ejb.update(equipment);
		}
		return "equipment.xhtml?faces-redirect=true&action=view&id=" + id;
	}

	public boolean isViewAction() {
		return "view".equals(action) && id != null;
	}

	public boolean isDisplayForm() {
		return ("edit".equals(action) && id != null) || "add".equals(action);
	}

	public String getAction() {
		return action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public Collection<Equipment> getEquipmentList() {
		return ejb.getList();
	}
	
	public List<SelectItem> getAvailableEquipment(){
		return ejb.getAvailable().stream().map(eq->{
			return new SelectItem(eq.getId(), eq.getName());
		}).collect(Collectors.toList());
	}

	public List<SelectItem> getEquipmentSelectItemList(){
		return ejb.getList().stream().map(eq->{
			return new SelectItem(eq.getId(), eq.getName(), null, !eq.isAvailable());
		}).collect(Collectors.toList());
	}
	
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Equipment getEquipment() {
		loadEquipment();
		return equipment;
	}

	public void setEquipment(Equipment equipment) {
		this.equipment = equipment;
	}

	private void loadEquipment() {
		if (equipment == null) {
			if (id != null)
				equipment = ejb.get(id);
			else
				equipment = new Equipment();
		}
	}
}

src/main/java/pl/edu/pwr/student200275/jsf/FacesOrderBean.java
package pl.edu.pwr.student200275.jsf;

import java.io.Serializable;
import java.util.Date;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.inject.Inject;

import pl.edu.pwr.student200275.ejb.EnterpriseCustomersBean;
import pl.edu.pwr.student200275.ejb.Logger;
import pl.edu.pwr.student200275.jpa.Order;

@ManagedBean
@RequestScoped
public class FacesOrderBean implements Serializable{
	private static final long serialVersionUID = -8928059076554502265L;

	@Inject
	private EnterpriseCustomersBean ejb;

	private boolean loaded = false;
	private Long id;
	private Date startDate;
	private Date endDate;
	private Long customerId;
	private String customerName;
	private Long equipmentId;
	private String equipmentName;
	
	public String save() {
		if (id == null) {
			ejb.createOrder(customerId, equipmentId);
		} else {
			ejb.updateOrder(id, customerId, equipmentId);
		}
		return "customer.xhtml?faces-redirect=true&id=" + customerId;
	}
	
	public Long getCustomerId() {
		loadOrder();
		return customerId;
	}

	public void setCustomerId(Long customerId) {
		this.customerId = customerId;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getEquipmentId() {
		loadOrder();
		return equipmentId;
	}

	private void loadOrder() {
		Logger.log("FacesOrderBean.loadOrder()." + System.nanoTime());
		if (id != null && !loaded) {
			Order order = ejb.getOrder(id);
			this.startDate = order.getStartDate();
			this.endDate = order.getEndDate();
			this.customerId = order.getCustomer().getId();
			this.customerName = order.getCustomer().getName();
			this.equipmentId = order.getEquipment().getId();
			this.equipmentName = order.getEquipment().getName();
			loaded = true;
		}
	}
	
	public String finish(Long id) {
		ejb.finishOrder(id);
		return "order.xhtml?faces-redirect=true&id=" + id;
	}

	public void setEquipmentId(Long equipmentId) {
		this.equipmentId = equipmentId;
	}

	public Date getStartDate() {
		loadOrder();
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		loadOrder();
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getCustomerName() {
		loadOrder();
		return customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public String getEquipmentName() {
		loadOrder();
		return equipmentName;
	}

	public void setEquipmentName(String equipmentName) {
		this.equipmentName = equipmentName;
	}
	
}

src/main/webapp/customer.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:jsf="http://xmlns.jcp.org/jsf">

<h:head>
	<title>Zarządzanie klientami</title>
	<f:metadata>
		<f:viewParam name="id" value="#{facesCustomerBean.id}" />
	</f:metadata>
</h:head>
<h:body>
	<h1>Zarządzanie klientem</h1>
	<h3>
		#{facesCustomerBean.customerName} <br />
		#{facesCustomerBean.customerStreet} <br />
		#{facesCustomerBean.customerZipCode} #{facesCustomerBean.customerCity}
		<br /> #{facesCustomerBean.customerPhone}
	</h3>
	<h:button outcome="editCustomer" value="Edycja">
		<f:param name="id" value="#{facesCustomerBean.id}" />
	</h:button><br/>
	<h:button outcome="orders" value="Historia zamówień">
		<f:param name="customerId" value="#{facesCustomerBean.id}" />
	</h:button><br/>
	<h:button outcome="editOrder" value="Nowe zamówienie" >
		<f:param name="customerId" value="#{facesCustomerBean.id}" />
	</h:button>
</h:body>

</html>

src/main/webapp/customers.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:jsf="http://xmlns.jcp.org/jsf">

<h:head>
	<title>Zarządzanie klientami</title>
</h:head>
<h:body>
	<h1>Zarządzanie klientami</h1>
			<h2>Lista klientów</h2>
			<h:dataTable value="#{facesCustomersBean.customers}" var="customer"
				border="7" cellpadding="3" title="Tabela klientów">
				<h:column>
					<f:facet name="header">Numer</f:facet>
					#{customer.id}.
				</h:column>
				<h:column>
					<f:facet name="header">Imię i nazwisko</f:facet>
					<h:link value="#{customer.name}" outcome="customer"
						includeViewParams="true">
						<f:param name="id" value="#{customer.id}" />
					</h:link>
				</h:column>
			</h:dataTable>
<!-- 			<h:button value="Dodaj nowego" outcome="editCustomer"> -->
<!-- 				<f:param name="action" value="add" /> -->
<!-- 			</h:button> -->
</h:body>

</html>

src/main/webapp/editCustomer.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:jsf="http://xmlns.jcp.org/jsf">

<h:head>
	<title>Zarządzanie klientami</title>
	<f:metadata>
		<f:viewParam name="id" value="#{facesCustomerBean.id}" />
	</f:metadata>
</h:head>
<h:body>
	<h1>Zarządzanie klientem</h1>
	<h:form>
		<h:inputHidden value="id" />
		<h:inputText value="#{facesCustomerBean.customerName}" />
		<br />
		<h:inputText value="#{facesCustomerBean.customerStreet}" />
		<br />
		<h:inputText value="#{facesCustomerBean.customerZipCode}" size="6" />
		<h:inputText value="#{facesCustomerBean.customerCity}" size="10" />
		<br />
		<h:inputText value="#{facesCustomerBean.customerPhone}" /> <br/>
		<h:commandButton action="#{facesCustomerBean.save}" value="Zapisz"/>
	</h:form>
</h:body>

</html>

src/main/webapp/editOrder.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:jsf="http://xmlns.jcp.org/jsf">

<h:head>
	<title>Zarządzanie zamówieniem klienta</title>
	<f:metadata>
		<f:viewParam name="id" value="#{facesOrderBean.id}" />
		<f:viewParam name="customerId" value="#{facesOrderBean.customerId}"/>
		<f:viewParam name="equipmentId" value="#{facesOrderBean.equipmentId}"/>
	</f:metadata>
</h:head>
<h:body>
	<h1>Zarządzanie zamówieniem klienta</h1>
	<h:form>
		<h:inputHidden value="id" />
		<h:selectOneMenu value="#{facesOrderBean.customerId}">
			<f:selectItems value="#{facesCustomersBean.customersSelectItemList}" />
		</h:selectOneMenu>
		<h:selectOneMenu value="#{facesOrderBean.equipmentId}">
			<f:selectItems value="#{facesEquipmentBean.equipmentSelectItemList}" />
		</h:selectOneMenu>
		<h:commandButton value="Zapisz"
			action="#{facesOrderBean.save}" />
	</h:form>
</h:body>

</html>

src/main/webapp/equipment.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:jsf="http://xmlns.jcp.org/jsf">
<f:metadata>
	<f:viewParam name="action" value="#{facesEquipmentBean.action}" />
	<f:viewParam name="id" value="#{facesEquipmentBean.id}" />
</f:metadata>

<h:head>
	<title>Zarządzanie sprzętem</title>
</h:head>
<h:body>
	<h1>Zarządzanie sprzętem</h1>
	<div style="display: flex; justify-content: space-evenly;">
		<div>
			<h2>Lista sprzętu</h2>
			<h:dataTable value="#{facesEquipmentBean.equipmentList}"
				var="equipment" border="7" cellpadding="3" title="Tabela sprzętu">
				<h:column>
					<f:facet name="header">Numer</f:facet>
					#{equipment.id}.
				</h:column>
				<h:column>
					<f:facet name="header">Nazwa</f:facet>
					<h:link value="#{equipment.name}" outcome="equipment"
						includeViewParams="true">
						<f:param name="action" value="view" />
						<f:param name="id" value="#{equipment.id}" />
					</h:link>
				</h:column>
				<h:column>
					<f:facet name="header">Dostępny</f:facet>
					<h:selectBooleanCheckbox value="#{equipment.available}"
						disabled="true" />
				</h:column>
			</h:dataTable>
			<h:button value="Dodaj nowy" outcome="equipment">
				<f:param name="action" value="add" />
			</h:button>
		</div>
		<div jsf:rendered="#{facesEquipmentBean.viewAction}">
			<h2>Detale sprzętu</h2>
			#{facesEquipmentBean.equipment.name}<br />
			<h:button value="Edytuj" outcome="equipment">
				<f:param name="action" value="edit" />
				<f:param name="id" value="#{facesEquipmentBean.equipment.id}" />
			</h:button>
		</div>
		<h:form rendered="#{facesEquipmentBean.displayForm}">
			<h2>Detale sprzętu</h2>
			<h:inputHidden value="#{facesEquipmentBean.equipment.id}" />
			<h:inputText value="#{facesEquipmentBean.equipment.name}" size="25" />
			<br />
			<h:commandButton value="Zapisz" action="#{facesEquipmentBean.save}" />
		</h:form>
	</div>
</h:body>

</html>

src/main/webapp/index.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">

<h:head>
	<title>Strona główna</title>
</h:head>
<h:body>
	<h1><h:link outcome="customers">Zarządzanie klientami</h:link></h1>
	<h1><h:link outcome="equipment">Zarządzanie sprzętem</h:link></h1>
</h:body>

</html>

src/main/webapp/order.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:jsf="http://xmlns.jcp.org/jsf">

<h:head>
	<title>Zarządzanie zamówieniem klienta</title>
	<f:metadata>
		<f:viewParam name="id" value="#{facesOrderBean.id}" />
	</f:metadata>
</h:head>
<h:body>
	<h1>Zarządzanie zamówieniem klienta</h1>
	<h3>
		Numer: #{facesOrderBean.id} <br /> 
		Imię i nazwisko: #{facesOrderBean.customerName} <br />
		Data wypożyczenia: #{facesOrderBean.startDate} <br />
		Data zwrotu: #{facesOrderBean.endDate} <br /> 
		Nazwa sprzętu: #{facesOrderBean.equipmentName} <br />
	</h3>
	<h:button outcome="editOrder" value="Edycja" rendered="#{facesOrderBean.endDate == null}">
		<f:param name="id" value="#{facesOrderBean.id}" />
	</h:button>
	<br />
	<h:form rendered="#{facesOrderBean.endDate == null}">
		<h:commandButton action="#{facesOrderBean.finish(facesOrderBean.id)}"
			value="Przyjmij zwrot zamówienia" />
	</h:form>
</h:body>
</html>

src/main/webapp/orders.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:jsf="http://xmlns.jcp.org/jsf">
<f:metadata>
	<f:viewParam name="customerId" value="#{facesOrdersBean.customerId}" />
</f:metadata>

<h:head>
	<title>Historia zamówień</title>
</h:head>
<h:body>
	<h1>Historia zamówień</h1>
	<h:dataTable value="#{facesOrdersBean.orders}" var="order" border="7"
		cellpadding="3" title="Historia zamówień">
		<h:column>
			<f:facet name="header">Numer</f:facet>
			<h:link value="#{order.id}." outcome="order"
				includeViewParams="true">
				<f:param name="id" value="#{order.id}" />
			</h:link>
		</h:column>
		<h:column>
			<f:facet name="header">Imię i nazwisko</f:facet>
			#{order.customer.name}
		</h:column>
		<h:column>
			<f:facet name="header">Data złożenia</f:facet>
			#{order.startDate}
		</h:column>
		<h:column>
			<f:facet name="header">Data oddania</f:facet>
			#{order.endDate}
		</h:column>
	</h:dataTable>
</h:body>
</html>